export const KAKAO_AUTH_URL = `https://kauth.kakao.com/oauth/authorize?
client_id=${process.env.KAKAO_REST_API_KEY}&
redirect_uri=${process.env.KAKAO_REDIRECT_URI}&
response_type=code`;
export const GOOGLE_AUTH_URL = `https://accounts.google.com/o/oauth2/v2/auth?
response_type=code&
scope=openid%20email&
client_id=${process.env.GOOGLE_CLIENT_ID}&
redirect_uri=${process.env.GOOGLE_REDIRECT_URI}`;
export const NAVER_AUTH_URL = `https://nid.naver.com/oauth2.0/authorize?
client_id=${process.env.NAVER_CLIENT_ID}&
redirect_uri=${process.env.NAVER_REDIRECT_URI}&
response_type=code`;
